// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_wxV-UgDbb58QApXVmAOAGI66geDpPE',
    appId: '1:1057633483665:web:c8de0fdfc61d57268b3830',
    messagingSenderId: '1057633483665',
    projectId: 'flutter-27f7f',
    authDomain: 'flutter-27f7f.firebaseapp.com',
    storageBucket: 'flutter-27f7f.firebasestorage.app',
    measurementId: 'G-ZDRNXSNW8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK_O6Z6xaHpGLMp0g7A21YSgzyK9Btgec',
    appId: '1:1057633483665:android:03e8090525ba64b38b3830',
    messagingSenderId: '1057633483665',
    projectId: 'flutter-27f7f',
    storageBucket: 'flutter-27f7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPQc-YPZmCNa1uhUNuPBXyutRYNbbkVqs',
    appId: '1:1057633483665:ios:bdeaea93f74b7a0d8b3830',
    messagingSenderId: '1057633483665',
    projectId: 'flutter-27f7f',
    storageBucket: 'flutter-27f7f.firebasestorage.app',
    iosBundleId: 'com.mycompany.todolist2024winter',
  );
}
