// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHMbINigVhKJxqzviX3F-GV-lmWgQ7yoU',
    appId: '1:657974930120:web:046dd612cc6d99a5b1d3fd',
    messagingSenderId: '657974930120',
    projectId: 'tictactoe-f7b2f',
    authDomain: 'tictactoe-f7b2f.firebaseapp.com',
    storageBucket: 'tictactoe-f7b2f.firebasestorage.app',
    measurementId: 'G-B96V62D254',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ25y6m_F8fC_mSNF_pYPfRR3HXZKjVsc',
    appId: '1:657974930120:android:c336b74edfcba18ab1d3fd',
    messagingSenderId: '657974930120',
    projectId: 'tictactoe-f7b2f',
    storageBucket: 'tictactoe-f7b2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ_gOVzh6N-a5qrFBebg5NUWNSUhLBJT0',
    appId: '1:657974930120:ios:11445ab41e07c935b1d3fd',
    messagingSenderId: '657974930120',
    projectId: 'tictactoe-f7b2f',
    storageBucket: 'tictactoe-f7b2f.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ_gOVzh6N-a5qrFBebg5NUWNSUhLBJT0',
    appId: '1:657974930120:ios:11445ab41e07c935b1d3fd',
    messagingSenderId: '657974930120',
    projectId: 'tictactoe-f7b2f',
    storageBucket: 'tictactoe-f7b2f.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHMbINigVhKJxqzviX3F-GV-lmWgQ7yoU',
    appId: '1:657974930120:web:715b9ca30d4863f9b1d3fd',
    messagingSenderId: '657974930120',
    projectId: 'tictactoe-f7b2f',
    authDomain: 'tictactoe-f7b2f.firebaseapp.com',
    storageBucket: 'tictactoe-f7b2f.firebasestorage.app',
    measurementId: 'G-326TMBCCV3',
  );
}
