// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfdFEwWXJm-nMefqPSPahMeSQZkw5P3Is',
    appId: '1:171815273670:web:93dc703443711b481803c7',
    messagingSenderId: '171815273670',
    projectId: 'hypergaragesale-b7353',
    authDomain: 'hypergaragesale-b7353.firebaseapp.com',
    storageBucket: 'hypergaragesale-b7353.firebasestorage.app',
    measurementId: 'G-D0N26324JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASXjTOXXlh_GE1dCjSrEyuRr9zqGgQRPM',
    appId: '1:171815273670:android:3aaa2e9a1de066eb1803c7',
    messagingSenderId: '171815273670',
    projectId: 'hypergaragesale-b7353',
    storageBucket: 'hypergaragesale-b7353.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlU4FUbkJ64xtFIb-IkWGE_ztfugRAnhw',
    appId: '1:171815273670:ios:51797f84167083711803c7',
    messagingSenderId: '171815273670',
    projectId: 'hypergaragesale-b7353',
    storageBucket: 'hypergaragesale-b7353.firebasestorage.app',
    androidClientId: '171815273670-uedp4n34295ft2ubqmqbig223dfecc3s.apps.googleusercontent.com',
    iosClientId: '171815273670-s91hadi688bp0ic14qmf4ngr2b8kc366.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperGarageSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlU4FUbkJ64xtFIb-IkWGE_ztfugRAnhw',
    appId: '1:171815273670:ios:51797f84167083711803c7',
    messagingSenderId: '171815273670',
    projectId: 'hypergaragesale-b7353',
    storageBucket: 'hypergaragesale-b7353.firebasestorage.app',
    androidClientId: '171815273670-uedp4n34295ft2ubqmqbig223dfecc3s.apps.googleusercontent.com',
    iosClientId: '171815273670-s91hadi688bp0ic14qmf4ngr2b8kc366.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperGarageSale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfdFEwWXJm-nMefqPSPahMeSQZkw5P3Is',
    appId: '1:171815273670:web:54541046585d9ace1803c7',
    messagingSenderId: '171815273670',
    projectId: 'hypergaragesale-b7353',
    authDomain: 'hypergaragesale-b7353.firebaseapp.com',
    storageBucket: 'hypergaragesale-b7353.firebasestorage.app',
    measurementId: 'G-RWV995EFD3',
  );

}